language: python
python:
 - 3.5
install:
 - pip install termcolor
 - pip install python-coveralls
 - pip install coverage
 - pip install coveralls
 - pip install pytest-cov
before_script:
 - git clone https://github.com/JihoYoo7/c4cs-w18-rpn.git
 - git checkout -qf CW7dAUqxMjAHTIZQFlt1fAs0aeCwjtcOE
 - py.test test_rpn.py --cov=rpn.py
script:
 - make test
 - coverage run test_rpn.py
 - py.test --cov=rpn.py
 - py.test --cov-report= --cov=rpn.py test_rpn.py/
 - py.test test_rpn.py --cov-report= --cov=rpn.py test_rpn.py/
after_sucess: 
 - coveralls
