language: python
python:
 - 3.5
install:
 - pip install termcolor
 - pip install python-coveralls
 - pip install coverage
 - pip install coveralls
 - pip install pytest-cov
script:
 - make test
 - coverage run test_rpn.py
 - coverage run --source=mypkg setup.py test
 - py.test --cov-rpn= --cov=myproj rpn.py/
after_sucess: 
 - coveralls
