language: python
python:
 - 3.5
install:
 - pip install termcolor
 - pip install python-coveralls
 - pip install coverage
script:
 - make test
 - coverage run test_rpn.py
 - py.test --cov=myproj tests/
after_sucess: 
 - coveralls
