language: python
python:
 - 3.5
install:
 - pip install termcolor
 - pip install python-coveralls
 - pip install coverage
script:
 - coverage run test_rpn.py
 - py.test coveralls/tests.py --doctest-modules -v --cov coveralls --cov-report term-missing
 - make test
after_success:
 - coveralls
