language: python
python:
 - 3.5
 - pypy-5.4
 - pypy3.3-5.2-alpha1
env:
  - $COVPYYAML=cov3-default,coveralls3
  - $COVPYYAML=cov4-pyyaml,coveralls4
  - $COVPYYAML=cov41-pyyaml,coveralls41
matrix:
  include:
    - python: 3.6
      env: $COVPYYAML=cov41-pyyaml,coveralls41
install:
 - pip install termcolor
 - pip install python-coveralls
 - pip install coverage
 - pip install tox
script:
 - make test
 - coverage run test_rpn.py
 - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$COVPYYAML
after_sucess: 
 - coveralls
