language: python
python:
 - 3.5
install:
 - pip install -e . --use-mirrors
 - pip install termcolor
 - pip install python-coveralls
 - pip install coverage
 - pip install coveralls
 - pip install pytest-cov
script:
 - make test
 - coverage run test_rpn.py
 - py.test --cov=rpn.py
 - py.test --cov-report= --cov=rpn.py test_rpn.py/
 - py.test test_rpn.py --cov-report= --cov=rpn.py test_rpn.py/
after_sucess: 
 - coveralls
